(() => {
  'use strict';
  const A = 'recursos-visuales/';
  const dialogues = [
    'Hola.',
    'Feliz cumpleaños. Espero que este sea un muy buen día para ti. Espero que estés rodeada de todas las personas que te quieren y que te aman. De verdad deseo que esta nueva etapa de tu vida esté llena de cosas bonitas.',
    'También espero que te hayan gustado los girasoles.Te deseo lo mejor.'
  ];
  const $ = (id) => document.getElementById(id);
  const screens = {dialogue: $('dialogue-screen'), menu: $('menu-screen'), game: $('game-screen')};
  let dialogueIndex = 0;
  function showScreen(name){Object.values(screens).forEach(s=>s.classList.add('is-hidden')); screens[name].classList.remove('is-hidden');}
  function renderDialogue(){ const text=$('dialogue-text'); text.textContent=dialogues[dialogueIndex]; $('dialogue-count').textContent=`${String(dialogueIndex+1).padStart(2,'0')} / ${dialogues.length}`; }
  function advanceDialogue(){if(dialogueIndex < dialogues.length-1){dialogueIndex++;renderDialogue();}else{localStorage.setItem('milena-dialogue-seen','1');showScreen('menu');}}
  function startDialogue(){dialogueIndex=0;renderDialogue();showScreen('dialogue');}
  $('dialogue-card').addEventListener('click', e=>{if(e.target.closest('.dialogue-actions'))return;advanceDialogue();}); document.addEventListener('keydown', e=>{if((e.key===' '||e.key==='Enter')&&!screens.dialogue.classList.contains('is-hidden')){if(e.target.closest('.dialogue-button'))return;e.preventDefault();advanceDialogue();}else if((e.key===' '||e.key==='ArrowUp')&&!screens.game.classList.contains('is-hidden')){e.preventDefault();runner.jump();}});
  $('dialogue-home').addEventListener('click', e=>{e.stopPropagation();showScreen('menu');});
  $('dialogue-hide').addEventListener('click', e=>{e.stopPropagation();localStorage.setItem('milena-dialogue-hidden','1');showScreen('menu');});
  $('replay-dialogue').addEventListener('click', e=>{e.stopPropagation();startDialogue();}); $('start-button').addEventListener('click', ()=>{showScreen('game');runner.start();}); $('restart-button').addEventListener('click', ()=>runner.start()); $('menu-button').addEventListener('click', ()=>{runner.stop();showScreen('menu');});

  const canvas=$('game-canvas'), ctx=canvas.getContext('2d'), playerElement=$('player-sprite'); let W=0,H=0,dpr=1;
  const runner = {running:false,raf:0,last:0,score:0,high:Number(localStorage.getItem('milena-high-score')||0),sunflowerRecord:Number(localStorage.getItem('milena-sunflower-record')||0),sunflowersCollected:0,speed:330,speedMultiplier:1,viewportScale:1,ground:0,groundOffset:0,groundImage:null,gravity:2000,jumpVelocity:840,jumpDuration:0,jumpHeight:0,compoundWidth:0,jumpTargetDistance:0,lastGroupWidth:0,coyoteTimer:0,player:{x:0,y:0,w:156,h:182,vy:0,onGround:true},obstacles:[],sunflowers:[],sunflowerIn:0,spawnIn:1.3,bonusUntil:0,playerImage:null,playerReady:false,
    resize(){dpr=Math.min(2,window.devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);this.viewportScale=W<=800?.6:1;this.ground=H-Math.min(86,Math.max(58,H*.105));this.player.w=156*this.viewportScale;this.player.h=182*this.viewportScale;this.player.x=Math.max(22,W*.1);if(this.player.onGround)this.player.y=this.ground-this.player.h;},
    async start(){this.stop();showScreen('game');this.resize();this.score=0;this.sunflowersCollected=0;this.speedMultiplier=1;this.speed=465*this.viewportScale;this.jumpVelocity=this.viewportScale<1?966*Math.sqrt(this.viewportScale):966;this.compoundWidth=(113+106*.5)*this.viewportScale;this.jumpTargetDistance=this.compoundWidth*1.1;this.lastGroupWidth=0;this.jumpDuration=(2*this.jumpVelocity)/this.gravity;this.jumpHeight=(this.jumpVelocity*this.jumpVelocity)/(2*this.gravity);this.obstacles=[];this.sunflowers=[];this.sunflowerIn=2+Math.random()*16;this.spawnIn=2.4;this.bonusUntil=0;this.groundOffset=0;this.coyoteTimer=0;this.player.vy=0;this.player.onGround=true;this.player.y=this.ground-this.player.h;playerElement.classList.add('is-hidden');$('score').textContent='00000';$('speed-value').textContent='1.0×';$('sunflower-count').textContent='0';$('sunflower-record').textContent=String(this.sunflowerRecord);$('high-score').textContent=String(this.high).padStart(5,'0');$('bonus-indicator').classList.add('is-hidden');$('game-over').classList.add('is-hidden');this.running=true;this.last=performance.now();try{if(!this.playerReady)await this.loadPlayer();}catch(e){console.warn('No se pudo cargar el GIF del avatar:',e);}if(!this.running)return;this.loadGround();playerElement.classList.remove('is-hidden');this.syncPlayerElement();this.raf=requestAnimationFrame(t=>this.loop(t));},
    stop(){this.running=false;cancelAnimationFrame(this.raf);playerElement.classList.add('is-hidden');},
    async loadPlayer(){const image=playerElement;const ready=new Promise((resolve,reject)=>{if(image.complete&&image.naturalWidth){this.playerImage=image;this.playerReady=true;resolve();return;}image.onload=()=>{if(!image.naturalWidth||!image.naturalHeight)reject(new Error('GIF vacío'));else{this.playerImage=image;this.playerReady=true;resolve();}};image.onerror=reject;});image.src=A+'avatar-runner-rapido-1.6x.gif';await ready;},
    loadGround(){if(this.groundImage)return;this.groundImage=new Image();this.groundImage.src=A+'paisaje-de-fondo-carrusel-secuencial.png?v=20260721-new';},
    jump(){if(this.running&&(this.player.onGround||this.coyoteTimer>0)){this.player.vy=-this.jumpVelocity;this.player.onGround=false;this.coyoteTimer=0;}},
    addObstacle(){const make=(type,x)=>{const img=new Image();img.src=A+(type==='box'?'obstaculo-1-caja.png':'obstaculo-2-mochila-removebg-preview.png');const scale=this.viewportScale,h=(type==='box'?87:96)*scale,w=(type==='box'?113:106)*scale;return{x,y:this.ground-h,w,h,img};};let count=1;if(this.speedMultiplier>=4)count=5+Math.floor(Math.random()*4);else if(this.speedMultiplier>=2)count=3+Math.floor(Math.random()*2);else if(Math.random()<.32)count=2;const firstType=Math.random()<.5?'box':'bag';const first=make(firstType,W+30);this.obstacles.push(first);for(let i=1;i<count;i++){const type=i%2===1?(firstType==='box'?'bag':'box'):firstType;this.obstacles.push(make(type,first.x+first.w*.5*i));}this.lastGroupWidth=first.w*(1+(count-1)*.5);},
    addSunflower(){const img=new Image();img.src=A+'girasoles-removebg-preview.png';const size=113*1.1*this.viewportScale;this.sunflowers.push({x:W+30,y:this.ground-size,w:size,h:size,img});},
    obstacleGap(){const tier=Math.floor(this.score/100);const horizontalReach=Math.max(this.jumpTargetDistance,this.speed*this.jumpDuration*1.65);return Math.max(horizontalReach+180,this.lastGroupWidth*1.1+220,450,680-tier*32);},
    scheduleNextSpawn(){this.addObstacle();this.spawnIn=this.obstacleGap()/this.speed;},
    speedTier(score){let tier=0;let threshold=100;while(tier<20&&score>=threshold){tier++;threshold*=2;}return tier;},
    loop(now){if(!this.running)return;const dt=Math.min(.032,(now-this.last)/1000);this.last=now;const multiplier=now<this.bonusUntil?2:1;this.score+=dt*10*multiplier;const tier=this.speedTier(this.score);this.speedMultiplier=Math.min(5,1+tier*.2);this.speed=465*this.speedMultiplier*this.viewportScale;this.groundOffset=(this.groundOffset+this.speed*dt+W)%W;this.spawnIn-=dt;this.sunflowerIn-=dt;if(this.spawnIn<=0)this.scheduleNextSpawn();if(this.sunflowerIn<=0){this.addSunflower();this.sunflowerIn=1.275+Math.random()*15.3;}const p=this.player;if(!p.onGround)this.coyoteTimer=Math.max(0,this.coyoteTimer-dt);p.vy+=this.gravity*dt;p.y+=p.vy*dt;if(p.y>=this.ground-p.h){p.y=this.ground-p.h;p.vy=0;p.onGround=true;this.coyoteTimer=.12;}this.obstacles.forEach(o=>o.x-=this.speed*dt);this.sunflowers.forEach(s=>s.x-=this.speed*dt);this.obstacles=this.obstacles.filter(o=>o.x+o.w>-30);this.sunflowers=this.sunflowers.filter(s=>s.x+s.w>-30);const hitbox={x:p.x+29,y:p.y+15,w:p.w-58,h:p.h-30};for(const o of this.obstacles){if(hitbox.x<o.x+o.w-8&&hitbox.x+hitbox.w>o.x+8&&hitbox.y<o.y+o.h&&hitbox.y+hitbox.h>o.y+8){this.end();return;}}for(let i=this.sunflowers.length-1;i>=0;i--){const s=this.sunflowers[i];if(hitbox.x<s.x+s.w&&hitbox.x+hitbox.w>s.x&&hitbox.y<s.y+s.h&&hitbox.y+hitbox.h>s.y){this.bonusUntil=now+5000;this.sunflowers.splice(i,1);this.sunflowersCollected++;if(this.sunflowersCollected>this.sunflowerRecord){this.sunflowerRecord=this.sunflowersCollected;localStorage.setItem('milena-sunflower-record',String(this.sunflowerRecord));}$('sunflower-count').textContent=String(this.sunflowersCollected);$('sunflower-record').textContent=String(this.sunflowerRecord);}}this.updateBonus(now);$('speed-value').textContent=`${this.speedMultiplier.toFixed(1)}×`;this.syncPlayerElement();this.draw();this.raf=requestAnimationFrame(t=>this.loop(t));},
    syncPlayerElement(){playerElement.style.left=`${this.player.x}px`;playerElement.style.top=`${this.player.y}px`;playerElement.style.width=`${this.player.w}px`;playerElement.style.height=`${this.player.h}px`;},
    updateBonus(now){const active=now<this.bonusUntil;const indicator=$('bonus-indicator');indicator.classList.toggle('is-hidden',!active);if(active)$('bonus-time').textContent=`${Math.ceil((this.bonusUntil-now)/1000)}s`;},
    draw(){ctx.clearRect(0,0,W,H);if(this.groundImage&&this.groundImage.complete&&this.groundImage.naturalWidth){const stripH=Math.min(86,H*.105),sourceH=92;for(let x=-this.groundOffset;x<W;x+=W){ctx.drawImage(this.groundImage,0,this.groundImage.naturalHeight-sourceH,this.groundImage.naturalWidth,sourceH,x,this.ground,W,stripH);}}for(const s of this.sunflowers){if(s.img.complete&&s.img.naturalWidth)ctx.drawImage(s.img,s.x,s.y,s.w,s.h);}for(const o of this.obstacles){if(o.img.complete&&o.img.naturalWidth)ctx.drawImage(o.img,o.x,o.y,o.w,o.h);} $('score').textContent=String(Math.floor(this.score)).padStart(5,'0');},
    end(){this.running=false;cancelAnimationFrame(this.raf);playerElement.classList.add('is-hidden');$('bonus-indicator').classList.add('is-hidden');const current=Math.floor(this.score);if(current>this.high){this.high=current;localStorage.setItem('milena-high-score',String(this.high));}$('final-score').textContent=current;$('final-high-score').textContent=this.high;$('high-score').textContent=String(this.high).padStart(5,'0');$('game-over').classList.remove('is-hidden');}
  };
  window.addEventListener('resize',()=>{if(!screens.game.classList.contains('is-hidden')){runner.resize();runner.syncPlayerElement();}}); canvas.addEventListener('pointerdown',()=>runner.jump());
  showScreen('menu');
})();
