server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; add_header Cache-Control "no-cache, no-store, must-revalidate"; add_header Pragma "no-cache"; add_header Expires "0"; }
  location ~* \.(?:html|css|js)$ { expires -1; add_header Cache-Control "no-cache, no-store, must-revalidate"; add_header Pragma "no-cache"; add_header Expires "0"; }
  location ~* \.(?:png|piskel|ico|svg)$ { expires 7d; add_header Cache-Control "public, max-age=604800"; }
  location ~ /\. { deny all; }
}
